### ISSUE TITLE
SDL_hidapi.c Checklist

### ISSUE THREAD

**Issue by flibitijibibo** [flibitijibibo/SDL-multihid#1]
- [x] Don't use SDL_hidapi.c for iOS, *BSD
- [x] Don't explicitly link to libusb (unless on *BSD)
- [x] Check CMake, autoconf on...
    - [x] Linux
    - [x] macOS
    - [x] MinGW - NOPE
- [x] hid_init tracking
- [x] Style cleanup
- [ ] Delete Valve hid cpp files
- [ ] Anything else...?

Stuff we're not doing:
- SDL_hidapi.c for premade VisualC, Xcode projects

**Comment by aeikum** [comment]
Pushed a fix for linking against libusb, 9c47fb0dc. I suspect you're better set up to do the rest, but let me know if I can help.

**Comment by aeikum** [comment]
Possibly one more item for the checklist, remove `linux/hid.cpp` from the repository as it's been superseded.

**Comment by flibitijibibo** [comment]
All the build system stuff should be good now - still need to test macOS/MinGW, but I didn't see anything that would break those two specifically.

The BSD CheckUSBHID patch for [this Bugzilla report](https://bugzilla.libsdl.org/show_bug.cgi?id=4737) needed a tweak to use `OR` instead of `or` to build on my setup.

**Comment by flibitijibibo** [comment]
macOS and MinGW have been tested - Windows comes really close to supporting it, but libusb's hid.c has some POSIX dependencies that need to get fixed first. The build system supports it, we just have to fix the source. That's for another time though!

@aeikum: If the latest revision works for you, I'll squash this down and update the Bugzilla patch.

**Comment by flibitijibibo** [comment]
This is now in upstream! Nuking the repo right after this post, but eh, may as well be thorough here...
